---
title: "A minimal example"
author:
  - "Yizeng Li"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: false
vignette: >
  %\VignetteIndexEntry{A minimal example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse   = TRUE,
  comment    = "#>",
  echo       = TRUE,
  message    = FALSE,
  warning    = FALSE,
  fig.align  = "center",
  fig.width  = 5,
  fig.height = 4,
  dpi        = 120
)
```

# Introduction

This short vignette demonstrates fitting a Likelihood-based Additive Single-Effect (LARSE) model using the *glmcs* pacakge. We simulate a sparse linear regression problem, fit with up to $L$ single-effect compoenetns, and visualize the results. 

## Simulate data

```{r simulate}
set.seed(42)

n <- 1000    # sample size
p <- 1000    # number of predictors
L <- 10      # number of single-effect components

theta_true <- rep(0, p)
theta_true[c(1, 2, 300, 400)] <- 1

X <- matrix(rnorm(n * p), nrow = n, ncol = p)
y <- drop(X %*% theta_true + rnorm(n, sd = 1.5))
```

## Fit the LASER model

```{r fit}
library(glmcs)
res <- glmcs(
  X              = X,
  y              = y,
  L              = L,
  family         = gaussian()
)
```


## Results















