# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_dispersion <- function(y, family, offset, approach = "pearson") {
    .Call(`_glmcs_update_dispersion`, y, family, offset, approach)
}

univariate_loglik_cox <- function(x, y, theta, offset, ties = "efron") {
    .Call(`_glmcs_univariate_loglik_cox`, x, y, theta, offset, ties)
}

univariate_loglik_glm <- function(x, y, family, theta, offset) {
    .Call(`_glmcs_univariate_loglik_glm`, x, y, family, theta, offset)
}

univariate_loglik <- function(x, y, family, theta, offset, ties) {
    .Call(`_glmcs_univariate_loglik`, x, y, family, theta, offset, ties)
}

univariate_irls_cox <- function(x, y, offset, ties = "efron", lambda = 0.0, tau = 1e-5, max_iter = 25L, tol = 1e-8) {
    .Call(`_glmcs_univariate_irls_cox`, x, y, offset, ties, lambda, tau, max_iter, tol)
}

univariate_irls_glm <- function(x, y, family, offset, lambda = 0.0, tau = 1e-5, max_iter = 25L, tol = 1e-8) {
    .Call(`_glmcs_univariate_irls_glm`, x, y, family, offset, lambda, tau, max_iter, tol)
}

univariate_fit <- function(x, y, family, offset, standardize = TRUE, ties = "efron", lambda = 0.0, tau = 0.5, null_threshold = 1e-6) {
    .Call(`_glmcs_univariate_fit`, x, y, family, offset, standardize, ties, lambda, tau, null_threshold)
}

single_effect_fit <- function(X, y, family, offset, standardize = TRUE, ties = "efron", lambda = 0.0, tau = 0.5, null_threshold = 1e-6) {
    .Call(`_glmcs_single_effect_fit`, X, y, family, offset, standardize, ties, lambda, tau, null_threshold)
}

additive_effect_fit <- function(X, y, L, family = NULL, standardize = TRUE, ties = "efron", lambda = 0.0, tau = 0.5, null_threshold = 1e-6, tol = 5e-2, max_iter = 100L) {
    .Call(`_glmcs_additive_effect_fit`, X, y, L, family, standardize, ties, lambda, tau, null_threshold, tol, max_iter)
}

