# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kl_divergence <- function(p, log_base = 2.718) {
    .Call(`_glmcs_kl_divergence`, p, log_base)
}

get_loglike <- function(X, y, family, theta, intercept, dispersion = 1.0) {
    .Call(`_glmcs_get_loglike`, X, y, family, theta, intercept, dispersion)
}

get_purity <- function(pos, X, R, squared = FALSE, n_purity = 100L) {
    .Call(`_glmcs_get_purity`, pos, X, R, squared, n_purity)
}

get_included <- function(fit, X, y, family, alpha = 0.05) {
    .Call(`_glmcs_get_included`, fit, X, y, family, alpha)
}

get_cs <- function(posterior_mat, keep, coverage = 0.95, X = NULL, R = NULL, check_symmetric = TRUE, min_abs_corr = 0.5, n_purity = 100L, squared = FALSE) {
    .Call(`_glmcs_get_cs`, posterior_mat, keep, coverage, X, R, check_symmetric, min_abs_corr, n_purity, squared)
}

get_glm_fit <- function(x, y, family, offset, standardize = TRUE, max_iter = 25L, tol = 1e-8) {
    .Call(`_glmcs_get_glm_fit`, x, y, family, offset, standardize, max_iter, tol)
}

get_cox_fit <- function(x, y, offset, standardize = TRUE, ties = "efron", max_iter = 25L, tol = 1e-8) {
    .Call(`_glmcs_get_cox_fit`, x, y, offset, standardize, ties, max_iter, tol)
}

null_glm_fit <- function(y, family, offset, max_iter = 25L, tol = 1e-8) {
    .Call(`_glmcs_null_glm_fit`, y, family, offset, max_iter, tol)
}

null_cox_fit <- function(y, offset, ties = "efron") {
    .Call(`_glmcs_null_cox_fit`, y, offset, ties)
}

update_intercept <- function(y, family, offset) {
    .Call(`_glmcs_update_intercept`, y, family, offset)
}

update_dispersion <- function(y, family, offset) {
    .Call(`_glmcs_update_dispersion`, y, family, offset)
}

get_ser_fit <- function(X, y, family, offset, standardize = TRUE, ties = "efron") {
    .Call(`_glmcs_get_ser_fit`, X, y, family, offset, standardize, ties)
}

get_laser_fit <- function(X, y, family, L = 10L, standardize = TRUE, ties = "efron", algorithm = "greedy", max_iter = 100L, step_size = 1.0, tol = 1.0, seed = NULL) {
    .Call(`_glmcs_get_laser_fit`, X, y, family, L, standardize, ties, algorithm, max_iter, step_size, tol, seed)
}

